import { WeeklyTimesheet, TimesheetEntry, User } from '@/types'

export const mockUsers: User[] = [
  {
    email: 'john@tentwenty.me',
    password: 'password123',
    name: 'John Doe',
  },
]

export const mockTimesheets: WeeklyTimesheet[] = [
  {
    id: 1,
    week: 1,
    dateRange: '1 - 5 January, 2024',
    startDate: '2024-01-01',
    endDate: '2024-01-05',
    status: 'completed',
    totalHours: 40,
  },
  {
    id: 2,
    week: 2,
    dateRange: '8 - 12 January, 2024',
    startDate: '2024-01-08',
    endDate: '2024-01-12',
    status: 'missing',
    totalHours: 40,
  },
  {
    id: 3,
    week: 3,
    dateRange: '15 - 19 January, 2024',
    startDate: '2024-01-15',
    endDate: '2024-01-19',
    status: 'incomplete',
    totalHours: 20,
  },
  {
    id: 4,
    week: 4,
    dateRange: '22 - 26 January, 2024',
    startDate: '2024-01-22',
    endDate: '2024-01-26',
    status: 'completed',
    totalHours: 40,
  },
  {
    id: 5,
    week: 5,
    dateRange: '28 January - 1 February, 2024',
    startDate: '2024-01-28',
    endDate: '2024-02-01',
    status: 'missing',
    totalHours: 0,
  },
]

export const mockEntries: TimesheetEntry[] = [
  // Week 1
  {
    id: 1,
    weekId: 1,
    date: '2024-01-01',
    displayDate: 'Jan 1',
    taskName: 'Homepage Development',
    project: 'Project Alpha',
    hours: 4,
    type: 'Development',
  },
  {
    id: 2,
    weekId: 1,
    date: '2024-01-01',
    displayDate: 'Jan 1',
    taskName: 'Homepage Development',
    project: 'Project Alpha',
    hours: 4,
    type: 'Bug fixes',
  },
  {
    id: 3,
    weekId: 1,
    date: '2024-01-02',
    displayDate: 'Jan 2',
    taskName: 'Homepage Development',
    project: 'Project Beta',
    hours: 4,
    type: 'Development',
  },
  {
    id: 4,
    weekId: 1,
    date: '2024-01-02',
    displayDate: 'Jan 2',
    taskName: 'API Integration',
    project: 'Project Alpha',
    hours: 4,
    type: 'Development',
  },
  {
    id: 5,
    weekId: 1,
    date: '2024-01-03',
    displayDate: 'Jan 3',
    taskName: 'Code Review',
    project: 'Project Beta',
    hours: 4,
    type: 'Review',
  },
  {
    id: 6,
    weekId: 1,
    date: '2024-01-03',
    displayDate: 'Jan 3',
    taskName: 'Bug Fixing',
    project: 'Project Alpha',
    hours: 4,
    type: 'Bug fixes',
  },
  {
    id: 7,
    weekId: 1,
    date: '2024-01-04',
    displayDate: 'Jan 4',
    taskName: 'Homepage Development',
    project: 'Project Beta',
    hours: 4,
    type: 'Development',
  },
  {
    id: 8,
    weekId: 1,
    date: '2024-01-04',
    displayDate: 'Jan 4',
    taskName: 'Design Review',
    project: 'Project Alpha',
    hours: 4,
    type: 'Review',
  },
  {
    id: 9,
    weekId: 1,
    date: '2024-01-05',
    displayDate: 'Jan 5',
    taskName: 'Documentation',
    project: 'Project Beta',
    hours: 4,
    type: 'Development',
  },
  {
    id: 10,
    weekId: 1,
    date: '2024-01-05',
    displayDate: 'Jan 5',
    taskName: 'Sprint Planning',
    project: 'Project Alpha',
    hours: 4,
    type: 'Meeting',
  },
  // Week 3 — incomplete, only some days filled
  {
    id: 11,
    weekId: 3,
    date: '2024-01-15',
    displayDate: 'Jan 15',
    taskName: 'Homepage Development',
    project: 'Project Alpha',
    hours: 4,
    type: 'Development',
  },
  {
    id: 12,
    weekId: 3,
    date: '2024-01-15',
    displayDate: 'Jan 15',
    taskName: 'Bug Fixing',
    project: 'Project Beta',
    hours: 4,
    type: 'Bug fixes',
  },
  {
    id: 13,
    weekId: 3,
    date: '2024-01-16',
    displayDate: 'Jan 16',
    taskName: 'API Integration',
    project: 'Project Alpha',
    hours: 4,
    type: 'Development',
  },
  {
    id: 14,
    weekId: 3,
    date: '2024-01-16',
    displayDate: 'Jan 16',
    taskName: 'Code Review',
    project: 'Project Beta',
    hours: 4,
    type: 'Review',
  },
  {
    id: 15,
    weekId: 3,
    date: '2024-01-17',
    displayDate: 'Jan 17',
    taskName: 'Documentation',
    project: 'Project Alpha',
    hours: 4,
    type: 'Development',
  },
]

export const mockProjects = [
  'Project Alpha',
  'Project Beta',
  'Project Gamma',
  'Project Delta',
]

export const mockWorkTypes = [
  'Development',
  'Bug fixes',
  'Review',
  'Meeting',
  'Documentation',
]
